<?php

/**
 * @file
 * Implementing our hooks.
 */
 use Drupal\Core\Routing\RouteMatchInterface;


/**
 * Implements hook_theme().
 */
function hello_world_example_theme($existing, $type, $theme, $path) {

  return [
    'days' => [
      'variables' => ['items' => [], 'title' => ''],
    ]
  ];
}



/**
 * Implements hook_help().
 */
function hello_world_example_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the helloworld module.
    case 'help.page.hello_world_example':
      $output = '';
      $output .= '<h3>' . t('Hello World Example') . '</h3>';
      $output .= '<p>' . t('This is the Help page for "Hello World Example" module.') . '</p>';
      $output .= '<h3>' . t('Examples') . '</h3>';

      return $output;

    default:
  }
}
